// {
//     "image": null,
//     "sonod_Id": "",
//     "unioun_name": "test",
//     "year": 2024,
//     "ut_name": null,
//     "ut_religion": "",
//     "sonod_name": "উত্তরাধিকারী সনদ",
//     "applicant_holding_tax_number": null,
//     "applicant_national_id_number": null,
//     "applicant_birth_certificate_number": null,
//     "applicant_passport_number": null,
//     "applicant_date_of_birth": null,
//     "family_name": null,
//     "Annual_income": null,
//     "Subject_to_permission": null,
//     "disabled": null,
//     "The_subject_of_the_certificate": null,
//     "Name_of_the_transferred_area": null,
//     "applicant_name": "kk",
//     "applicant_second_name": null,
//     "applicant_name_of_the_organization": null,
//     "organization_address": null,
//     "alive_status": "1",
//     "applicant_gender": null,
//     "applicant_marriage_status": null,
//     "ut_father_name": null,
//     "ut_mother_name": null,
//     "applicant_father_name": null,
//     "applicant_mother_name": null,
//     "applicant_occupation": null,
//     "applicant_education": null,
//     "applicant_religion": null,
//     "applicant_resident_status": "স্থায়ী",
//     "applicant_owner_type": null,
//     "applicant_vat_id_number": null,
//     "applicant_tax_id_number": null,
//     "applicant_type_of_business": null,
//     "applicant_type_of_businessKhat": null,
//     "applicant_type_of_businessKhatAmount": null,
//     "successor_father_alive_status": null,
//     "successor_mother_alive_status": null,
//     "utname": "dfg",
//     "ut_grame": "k",
//     "ut_word": "3",
//     "ut_post": "k",
//     "ut_thana": "kk",
//     "ut_district": "kk",
//     "applicant_present_village": null,
//     "applicant_present_road_block_sector": null,
//     "applicant_present_word_number": "4",
//     "applicant_present_district": null,
//     "applicant_present_Upazila": null,
//     "applicant_present_post_office": null,
//     "applicant_permanent_village": null,
//     "applicant_permanent_road_block_sector": null,
//     "applicant_permanent_word_number": "4",
//     "applicant_permanent_district": null,
//     "applicant_permanent_Upazila": null,
//     "applicant_permanent_post_office": null,
//     "last_years_money": 0,
//     "applicant_mobile": "kkkkkkkkkkk",
//     "applicant_email": null,
// "applicant_birth_certificate_attachment": null,
//     "prottoyon": null,
//     "orthoBchor": "2023-24",
//     "stutus": "Prepaid",
//     "payment_status": "Unpaid",
//     "successors": [
//         {
//             "w_id": 0,
//             "w_name": "dfsgdf",
//             "w_relation": "কন্যা",
//             "w_age": "2024-06-14",
//             "w_nid": "sdfgfdg"
//         },
//         {
//             "w_name": "",
//             "w_relation": "",
//             "w_age": "",
//             "w_nid": "",
//             "w_id": 1
//         }
//     ],
//     "charages": {
//         "sonod_fee": 1,
//         "vatAmount": null,
//         "taxAmount": null,
//         "pesaKor": 0,
//         "service": null,
//         "tradeVat": 15,
//         "totalamount": 1,
//         "last_years_money": 0
//     }
// }
